# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    packages:
    - libv8-dev
    - libudunits2-dev
    - libgdal-dev
    - libproj-dev
  homebrew:
    packages:
    - udunits
jobs:
  include:
  - r: devel
  - os: osx
  - r: release